"""Sends the MOM email to stakeholders via SendGrid."""
import os
import httpx
import json

SENDGRID_API_KEY = os.environ["SENDGRID_API_KEY"]
FROM_EMAIL = os.environ.get("MOM_FROM_EMAIL", "meetingmind@yourdomain.com")


def _format_mom_html(mom: dict) -> str:
    ai = mom.get("action_items", [])
    action_items_html = "".join(
        f"<li><b>{a['assigned_to']}</b>: {a['description']} (by {a['deadline']}, {a['priority']} priority)</li>"
        for a in ai
    )
    decisions_html = "".join(f"<li>{d['description']}</li>" for d in mom.get("decisions", []))

    return f"""
    <h2>{mom.get('title', 'Meeting Summary')}</h2>
    <p><i>{mom.get('date')} — {mom.get('duration_minutes')} minutes</i></p>
    <p>{mom.get('executive_summary', '')}</p>
    <h3>Decisions</h3><ul>{decisions_html}</ul>
    <h3>Action Items</h3><ul>{action_items_html}</ul>
    <p><small>Generated by MeetingMind</small></p>
    """


async def send_mom_email(to_emails: list[str], mom: dict, meeting_title: str):
    payload = {
        "personalizations": [{"to": [{"email": e} for e in to_emails]}],
        "from": {"email": FROM_EMAIL, "name": "MeetingMind"},
        "subject": f"MOM: {meeting_title}",
        "content": [{"type": "text/html", "value": _format_mom_html(mom)}],
    }
    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.post(
            "https://api.sendgrid.com/v3/mail/send",
            json=payload,
            headers={"Authorization": f"Bearer {SENDGRID_API_KEY}"},
        )
        resp.raise_for_status()
